### ISSUE TITLE
Cannot read properties of undefined (reading 'ship') when trying to start simulation

### ISSUE THREAD

**Issue by Misaka-0x447f** [tiktrimo/EVE-Fitting.js#14]
I imported two ship and pressed import fits from above. This is whats happening, to your script.

```
SimulationPanel.jsx:73  Uncaught TypeError: Cannot read properties of undefined (reading 'ship')
    at SimulationPanel.jsx:73:24
```

Also, demo simulation works fine.

![image](https://github.com/user-attachments/assets/a46791f4-27a5-4225-a4a8-35a59702b832)

"Download error log" only produce this in console (and I cannot copy to here so I will give out what imported):
![image](https://github.com/user-attachments/assets/92ade4c7-5d99-4f56-9ebe-bf1af526fbdd)

## Imported fitting 1
```
[Gila, 1/2深渊盾扩毒蜥级]
Damage Control II
Drone Damage Amplifier II
Drone Damage Amplifier II

Compact Multispectrum Shield Hardener
Compact Multispectrum Shield Hardener
Medium Ancillary Shield Booster
Large F-S9 Regolith Compact Shield Extender
Large F-S9 Regolith Compact Shield Extender
50MN Y-T8 Compact Microwarpdrive

Drone Link Augmentor I
Prototype 'Arbalest' Rapid Light Missile Launcher
Prototype 'Arbalest' Rapid Light Missile Launcher
Prototype 'Arbalest' Rapid Light Missile Launcher
Prototype 'Arbalest' Rapid Light Missile Launcher

Medium Core Defense Field Extender I
Medium Core Defense Field Extender I
Medium Core Defense Field Extender I



Caldari Navy Vespa x8

Cap Booster 100 x33
Caldari Navy Scourge Light Missile x1576
Nanite Repair Paste x10
```
## Imported fitting 2
```
[Tormentor, 刷怪巨神兵]
Small Armor Repairer I
Extruded Compact Heat Sink
Extruded Compact Heat Sink
Damage Control I

Small Capacitor Booster I
5MN Cold-Gas Enduring Microwarpdrive

Small Focused Modulated Pulse Energy Beam I
Small Focused Modulated Pulse Energy Beam I
Small Focused Modulated Pulse Energy Beam I

Small Explosive Armor Reinforcer I
Small Trimark Armor Pump I
Small Trimark Armor Pump I




Radio S x3
Multifrequency S x3
Cap Booster 200 x9
Calm Exotic Filament x1
```

## Env
Not working in both following browser:
- Firefox 128.0.3 (64-bit)
  - `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0`
- Edge Version 127.0.2651.86 (Official build) (64-bit)
  - `
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0'
`

## Full console log
[evefittingjs.web.app-1722935580266.log](https://github.com/user-attachments/files/16508212/evefittingjs.web.app-1722935580266.log)

**Comment by tiktrimo** [comment]
Fixed! please check on the live website ([commit detail](https://github.com/tiktrimo/EVE-Fitting.js/commit/2295aaeef2d8619b0e0916b30a910818d873f1a0))
